---
- name: Validate and setup dynamic hosts
  hosts: localhost  # Only runs on AWX server
  tasks:
    - name: Fail if no hosts provided
      fail:
        msg: "No hosts specified! Use the survey to enter target servers."
      when: runtime_servers == "unspecified"

    - name: Add dynamic hosts
      add_host:
        name: "{{ item }}"
        groups: apache_servers
        # Explicitly set connection vars
        ansible_connection: ssh
        ansible_user: vagrant  # Default user, override in survey if needed
      loop: "{{ runtime_servers.split(',') }}"

- name: UnInstall Apache on runtime hosts
  hosts: apache_servers  # Only runs on dynamically added hosts
  become: yes
  become_method: sudo
  tasks:
    - name: Uninstall Apache
      yum:
        name: httpd
        state: absent

    
