---
- name: Setup dynamic hosts with credentials
  hosts: localhost
  tasks:
    - name: Validate inputs
      assert:
        that:
          - runtime_servers != "unspecified"
          - runtime_ssh_user is defined
        fail_msg: "Missing required host or user input"

    - name: Add dynamic hosts with credentials
      add_host:
        name: "{{ item }}"
        groups: runtime_servers
        ansible_host: "{{ item }}"
        ansible_user: "{{ runtime_ssh_user }}"
        ansible_ssh_pass: "{{ runtime_ssh_pass | default(omit) }}"
        ansible_become_pass: "{{ runtime_become_pass | default(omit) }}"
      loop: "{{ runtime_servers.split(',') }}"

- name: Install software
  hosts: runtime_servers
  become: true
  gather_facts: false  # Skip if not needed
  tasks:
    - name: Install Nginx/Apache
      package:
        name: "{{ package_to_install | default('nginx') }}"
        state: present

    - name: Start service
      service:
        name: "{{ package_to_install | default('nginx') }}"
        state: started
        enabled: yes
